pipeline:
  name: Build sample_app
  identifier: Build_sample_app_1755981438870
  projectIdentifier: bofa158ip22
  orgIdentifier: bofa158org
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: Test
                  name: Test_1
                  identifier: Test_1
                  spec:
                    shell: Sh
                    command: pip install pytest & cd ./python-tests
                    intelligenceMode: true
              - stepGroup:
                  name: Compiler
                  identifier: Compiler
                  steps:
                    - step:
                        name: CompileMe
                        identifier: CompileMe
                        template:
                          templateRef: Compile_Application
                          versionLabel: v0.1
              - step:
                  name: owasp
                  identifier: owasp
                  template:
                    templateRef: owasp
                    versionLabel: v0.1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        repoName: harnessrepo
        build: <+input>
        sparseCheckout: []
